-- TODO: THIS IS CREATE TABLE FOR DATETIME PURPOSE

-- CREATE TABLE USERS( NAME VARCHAR(30),
-- COL1  DATE,
-- COL2  TIME,
-- COL3  DATETIME
-- );

-- TODO: ADD SOME VALUE
-- INSERT INTO USERS (NAME,COL1,COL2,COL3 )
-- VALUES('hiitesh','2020-08-14','10:12:22','2021-08-18 11:08:32');

-- TODO: GET THE DATETIME

-- SELECT NAME,COL3 FROM USERS;

-- SELECT NAME,DATE_FORMAT(COL3,'%m/%d/%Y') FROM USERS;

-- SELECT NAME,DATE_FORMAT(COL3,'%m/%d/%Y')AS DATE  FROM USERS;
