-- this query use for show DATABASE

-- SHOW DATABASES;

-- this is USE for create databsae

-- CREATE DATABASE PHOTO_STORE;  
-- SHOW DATABASES;

-- this is use for select database

-- SELECT DATABASE() ;

-- this is used for use current DATABASE

-- USE PHOTO_STORE;
-- SELECT DATABASE(); 



-- This query wirten for create TABLE purpose

-- CREATE TABLE cameras(
--     model_name VARCHAR(30),
--     quantity INT

-- );

-- DESC cameras;

-- SHOW TABLES;
-- DROP TABLE CAMERAS;
-- SHOW TABLES;

-- CREATE TABLE CANON_CAMERAS(
--     MODEL_NO VARCHAR(30),
--     QUANTITY INT

-- );

-- DESC CANON_CAMERAS;

-- THIS USEING FOR INSERT DATA IN TABLE COLOUM

-- INSERT INTO CANON_CAMERAS(MODEL_NO,QUANTITY)
-- VALUES("70-D",12),("80D",19),("EOS-R",25),("EOS-R5",80),("EOS-R6",50);

-- USE THIS FOR SHOW ALL DATA IN TABLES
-- SELECT *FROM CANON_CAMERAS; 

-- USE FOR PARTICULAR COLUME
-- SELECT MODEL_NO FROM CANON_CAMERAS;



-- SELECT MODEL_NO , QUANTITY FROM CANON_CAMERAS 
-- WHERE MODEL_NO ="80D";

-- SELECT MODEL_NO ,QUANTITY FROM CANON_CAMERAS WHERE QUANTITY >= 50;


